#!/bin/sh
set -e

RED=$(tput setaf 1)
RESET=$(tput sgr0)

echo "${RED}Warning: On April 23rd, 2025, we'll be moving all 0.1.1 features to 0.1.0 to service them in a long term release manner. In the same day, we'll end support for this series. You are advised to upgrade to the latest supported series to continue receiving support from us.${RESET}"
