.\" 
.\"    Nitrocid KS  Copyright (C) 2018-2025  Aptivi
.\" 
.\"    Nitrocid KS is free software: you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    Nitrocid KS is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\"

.TH ks-rkm 1 "25 Nov 2025" "0.2.0" "Nitrocid KS - Remote Kernel Manager"
.SH NAME
ks-rkm \- simulates our future-planned kernel, Nitrocid Kernel \- Remote Kernel Manager
.SH SYNOPSIS
ks-rkm [args]
.SH DESCRIPTION
ks-rkm is the remote kernel manager command-line utility for Nitrocid KS and its RPC feature. It allows you to perform operations on the remote host that is running the RPC server within Nitrocid KS.
.SH DOCUMENTATION
The whole documentation can be found in https://aptivi.gitbook.io/nitrocid-ks-manual.
.SH AUTHOR
Aptivi (ceo AT aptivi DOT anonaddy DOT com)
