name: Build Project (for Launchpad PPA)

on:
  push:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas", "v0.1.3.x-saas" ]
  pull_request:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas", "v0.1.3.x-saas" ]


jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo NEEDRESTART_SUSPEND=1 apt update
          sudo NEEDRESTART_SUSPEND=1 apt install devscripts debhelper-compat dput build-essential equivs
          sudo NEEDRESTART_SUSPEND=1 mk-build-deps -i

      - name: Add GitHub Package Registry to get access to beta builds
        run: dotnet nuget add source --username AptiviCEO --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aptivi/index.json"
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
          make init-offline
          make clean
        
      - name: Try to build
        run: |
          sudo ip netns exec no-net make all-offline
