name: Build Project (Release)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Add GitHub Package Registry to get access to beta builds
        run: dotnet nuget add source --username AptiviCEO --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aptivi/index.json"
      - name: Solution Compilation (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: ./tools/build.cmd Release -p:ContinuousIntegrationBuild=true
      - name: Solution Compilation (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: make rel-ci
      - name: Testing
        run: dotnet test --no-build --configuration Release
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: unit-test-log-${{ matrix.runs-on }}
          path: "private/Nitrocid.Tests/KSTest/net8.0/UnitTestDebug.log"
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: unit-test-log-ms-${{ matrix.runs-on }}
          path: "private/Nitrocid.Tests/KSTest/net8.0/TestResults"
