name: Push to Docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v0.1.*'

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Prepare Docker (auth)
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: eofla/nitrocid
      - name: Add GitHub Package Registry to get access to beta builds
        run: dotnet nuget add source --username AptiviCEO --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aptivi/index.json"
      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          push: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
