name: Prepare release (canary)

on:
  push:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas" ]
  pull_request:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas" ]
    
jobs:
  build:

    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Release Asset Preparation
        run: |
          cmd.exe /c "tools\build.cmd Debug -p:ContinuousIntegrationBuild=true"
          dotnet build -p:Configuration=Debug -p:Platform=x64 public/Nitrocid.Installers/Nitrocid.Installer.sln
          dotnet build -p:Configuration=Debug -p:Platform=ARM64 public/Nitrocid.Installers/Nitrocid.Installer.sln
          Move-Item public/Nitrocid.Installers/Nitrocid.InstallerBundle/bin/x64/Debug/Nitrocid.InstallerBundle.exe vnd/nitrocid-win-x64-installer.exe
          Move-Item public/Nitrocid.Installers/Nitrocid.InstallerBundle/bin/ARM64/Debug/Nitrocid.InstallerBundle.exe vnd/nitrocid-win-arm64-installer.exe
      - uses: actions/upload-artifact@v4
        with:
          name: installer-x64-msi
          path: "vnd/nitrocid-win-x64-installer.exe"
      - uses: actions/upload-artifact@v4
        with:
          name: installer-arm64-msi
          path: "vnd/nitrocid-win-arm64-installer.exe"
      - uses: actions/upload-artifact@v4
        with:
          name: nks-build
          path: "public/Nitrocid/KSBuild"
      - uses: actions/upload-artifact@v4
        with:
          name: nks-analyzer
          path: "public/Nitrocid/KSAnalyzer"
      - name: Package Publication
        run: |
          dotnet nuget add source --username AptiviCEO --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aptivi/index.json"
          cmd.exe /C "tools\push.cmd ${{ secrets.GITHUB_TOKEN }} github"
